Use container query hook
react-container-query/react-container-query pull request #93
Opened 2021-02-09 18:39 UTC by mayank23

Hi, this is my PR to add the useContainerQuery Hook. Added Readme update + tests which are all were passing locally. 

I kept getting the `ResizeObserverLoop` Limit exceeded error when running tests, so added the fix in which schedules the observer callback in an animation frame. I used the PR code from https://github.com/react-container-query/react-container-query/pull/77 . See https://github.com/react-container-query/react-container-query/issues/70 for additional info.

2021-02-18 21:29 UTC, pixelbandito requested changes
Changes requested:
1. Revert the update to .gitignore
2. Remove a comment referring to the PR
3. Add server tests

Otherwise, this looks very nice. 👏 👏 👏

2021-02-18 21:29 UTC, pixelbandito commented on test/server/index.js
> +});
I ran the code locally, and added a couple of tests. Good news: the code passed without modification.

Would you add the server rendering tests to your PR branch?

Here's what I did, pretty minimal, but it works if you want to copy-paste it.

```js
describe('useContainerQuery', function () {

  const query = {
    mobile: { maxWidth: 399 },
    desktop: { minWidth: 400 }
  };

  function renderContainerToStaticMarkup({ initialSize }) {
    const Container = () => {
      const [params, containerRef] = useContainerQuery(query, initialSize);

      return React.createElement(
        'div',
        {
          ref: containerRef
        },
        JSON.stringify(params)
      );
    };

    return renderToStaticMarkup(React.createElement(Container));
  }

  it('no matches with no initial widths', function () {
    const output = renderContainerToStaticMarkup({});
    expect(output).toBe('<div>{}</div>');
  });

  it('sets "mobile" to true at small sizes', function () {
    const zeroWidthOutput = renderContainerToStaticMarkup({ initialSize: { width: 399 } });
    const maximumMobileWidthOutput = renderContainerToStaticMarkup({ initialSize: { width: 0 } });

    expect(zeroWidthOutput).toBe('<div>{&quot;mobile&quot;:true,&quot;desktop&quot;:false}</div>');
    expect(maximumMobileWidthOutput).toBe('<div>{&quot;mobile&quot;:true,&quot;desktop&quot;:false}</div>');
  });

  it('sets "desktop" to true at large sizes', function () {
    const output = renderContainerToStaticMarkup({ initialSize: { width: 400 } });
    expect(output).toBe('<div>{&quot;mobile&quot;:false,&quot;desktop&quot;:true}</div>');
  });
});
```

2021-02-18 21:29 UTC, pixelbandito commented on src/index.tsx
> +  // @ts-ignore
The ts-ignore is ugly, but I think we'll have to update typescript and/or types/react, types/react-dom to get it to work.

That should probably be outside the scope of this change, so I'll try to have a look at it later.

2021-02-22 19:27 UTC, mayank23 commented
@pixelbandito , made changes based on the feedback 😄 

Also, speaking of the server rendering, since container query core is updated schedule the resize observer callbacks using `window.requestAnimationFrame` -  could this be a breaking change since `window` wouldn't be available in server side rendering I think? If so, maybe this release should be a major version bump 🤔

However I see that ResizeObserverLite also uses window.ResizeObserver or switches to using element-resize-observer which both would only work in the browser and not server side I think 
https://github.com/react-container-query/resize-observer-lite/blob/master/src/index.ts#L10-L16

TLDR: not sure if the existing react-container-query would actually work with server side rendering

2021-02-23 16:41 UTC, pixelbandito commented
> TLDR: not sure if the existing react-container-query would actually work with server side rendering

I didn't write the original code, but afaik, the server-side rendering doesn't do any resize watching. It's only responsible for rendering using the initial width argument to the hook or component.

The tests seem to work as far as that goes, so I think it's ok.

2021-02-23 19:49 UTC, mayank23 commented
Alright great! Should be good to go then 😄 🥳

2021-02-25 15:09 UTC, merged